# Generated by Django 4.1.6 on 2023-02-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=200)),
                ('sponsorship_type', models.CharField(max_length=200)),
            ],
        ),
    ]
