name: Update server
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Update server
    runs-on: ubuntu-latest
    steps:
      - name: Updating latest changes on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            pm2 delete advaita --silent
            cd advaita
            git reset --hard HEAD
            git clean -f -d
            git pull
            pm2 start manage.py --interpreter=./venv/bin/python --name advaita -- runserver
